In [1]:
print("hello world")
# https://zhuanlan.zhihu.com/p/32242331

hello world


In [2]:
#numpy（Numerical Python）提供了python对多维数组对象的支持:ndarray，具有矢量运算能力，快速、节省空间
# ndarray：N维数组对象（矩阵），所有元素必须是相同类型。
# ndim属性，表示维度个数；shape属性，表示各维度大小；dtype属性，表示数据类型
import numpy as np
import numpy.linalg as lg
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
#打印数组
print(data)
#打印数组的维度
print(data.ndim)
#打印数组各个维度的长度。shape是一个元组
print(data.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [3]:
#创建一维长度为6的，元素都是0一维数组
print(np.zeros(6))
#创建一维长度为2，二维长度为3的二维0数组
print(np.zeros((2,3)))
#创建一维长度为2，二维长度为3的二维1数组
print(np.ones((2,3)))
# 使用arrange生成连续元素
print(np.arange(6))
print(np.arange(5,10))

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5]
[5 6 7 8 9]


In [4]:
#矩阵的转置
data = np.array([[1,2,3],[4,5,6]])
print(data.transpose())
print(data.T)
#设A是数域上的一个n阶方阵，若在相同数域上存在另一个n阶矩阵B，使得： AB=BA=E。 则我们称B是A的逆矩阵，而A则被称为可逆矩阵。
#求矩阵的逆需要先导入numpy.linalg，用linalg的inv函数来求逆。矩阵求逆的条件是矩阵应该是方阵。
# numpy.linalg.LinAlgError: Singular matrix 不可逆矩阵
data = np.matrix([[1,2],[-1,-3]])
print(data)
print(lg.inv(data))
# 3阶单位矩阵
data = np.eye(3) 
# 单位矩阵的逆为他本身
print(lg.inv(data))

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[ 1  2]
 [-1 -3]]
[[ 3.  2.]
 [-1. -1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# 4x+6y=48
# 2x+10y=52
# A*M = B
# 构造系数矩阵 A
A = np.array([[4,6],[2,10]])
B = np.array([48,52])
print(B.T)
print(np.linalg.solve(A,B.T))
# 通过求逆矩阵求解
A_inv=np.linalg.inv(A)
print(np.dot(A_inv,B))

[48 52]
[6. 4.]
[6. 4.]
